defaults: 
- submitit_slurm

timeout_min: 120
cpus_per_task: 6
tasks_per_node: 1
nodes: 1
gres: gpu:1
partition: 
account: ovm@v100
constraint:
setup:
  - source ${oc.env:HOME}/.bashrc
  - conda activate sinterp