defaults:
- solver: euler_maruyama
- _self_


num_workers: ${oc.decode:${oc.env:SLURM_CPUS_PER_TASK,4}}
limit_train_batches:
limit_val_batches: 


run_id: ???
classifier_id: e450563e40e14658b71a1d4b9c4f7e21

batch_size: 256

n_sampling_steps: 200
time_padding: 1e-4

limit_generate_batches: 

mlflow:
  tracking_uri: sqlite:///${oc.env:WORK}/mnistinterp/mlflow/db.sqlite
  experiment_name: mnistinterp_inference
  run_name: inference
  artifact_location: ${oc.env:WORK,.}/mnistinterp/mlflow/artifacts


hydra:
  job:
    chdir: true
  run:
    dir: ${oc.env:SCRATCH,"."}/run/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${oc.env:SCRATCH,"."}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}